name: Simulação de Deploy SISRH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build do projeto
        run: mvn clean install

      - name: Simular Deploy
        run: echo "Deploy concluído com sucesso!"
